### ISSUE TITLE
retorno da API

### ISSUE THREAD

**Issue by JeanGoncalves** [cubonetwork/front-end-challenge#2]
Não sei se faz parte do teste tratar o retorno da API, mas o `/pie-chart` não está retornando um JSON correto pois está faltando as vírgulas.
Está retornado:
``` json
{
    percent : 18.00
    hour : "12:00"
    currency : 350.00
}
```
ao invés de 
``` json 
{
    percent : 18.00 ,
    hour : "12:00" ,
    currency : 350.00
}
```

**Comment by LFeh** [comment]
c/c @danilocubo 😄

**Comment by danilocubo** [comment]
Fala @JeanGoncalves, sim faz parte do teste. 
Criamos este teste na época que estávamos recrutando front-enders aqui para o Cubo e um dos objetivos é certificar que a pessoa saiba não só desenvolver um bom layout como comunicar com backend através de APIs, entender o que é um JSON (**válido**), etc. 
Então foi tipo uma _"pegadinha"_ mesmo... hehe :grimacing:

As versões corretas das APIs:
https://of900lijd5.execute-api.us-east-1.amazonaws.com/v2/front-end/pie-chart
https://of900lijd5.execute-api.us-east-1.amazonaws.com/v2/front-end/grid-people

**Comment by reebr** [comment]
@LFeh @danilodevhub 

No README ainda estão sendo referenciados os links incorretos.
